steps:
- name: 'docker/compose'
  args: ['up', '-d']
- name: 'docker/compose'
  args: ['ps']
- name: 'node:12-alpine'
  entrypoint: /bin/sh
  args: ['-c', 'ls -al && yarn && yarn test']
- name: 'docker'
  args: ['build', '--network', 'host', '.']

