steps:
- name: 'docker/compose'
  args: ['up', '-d']
- name: 'docker/compose'
  args: ['ps']
- name: 'docker'
  args: ['build', '-t', 'houstonj1/cloudbuild-compose:latest', '.']
  env:
    - 'DOCKER_BUILDKIT=1'
- name: 'docker'
  args: ['run', '--network', 'host', 'houstonj1/cloudbuild-compose:latest', 'yarn test']

