steps:
- name: 'docker/compose'
  args: ['up', '-d']
- name: 'docker/compose'
  args: ['ps']
- name: 'docker'
  args: ['network', 'ls']
- name: 'node:12-alpine'
  entrypoint: /bin/sh
  args:
    - -c
    - |
      yarn
      yarn test
  env:
    - 'PG_HOST=postgres'
- name: 'docker'
  args: ['build', '-t', 'houstonj1/cloudbuild-compose:latest', '.']
  env:
    - 'DOCKER_BUILDKIT=1'
- name: 'docker'
  entrypoint: /bin/sh
  args:
    - -c
    - |
      docker ps -a
      docker run --network host houstonj1/cloudbuild-compose:latest yarn test

