steps:
- name: 'docker/compose'
  entrypoint: /bin/sh
  args:
    - -c
    - |
      cat <<EOF >> docker-compose.yml
      networks:
        default:
          external:
            name: cloudbuild
      EOF
      cat docker-compose.yml
      docker-compose up -d
- name: 'docker/compose'
  args: ['ps']
- name: 'docker'
  args: ['network', 'ls']
- name: 'node:12-alpine'
  entrypoint: /bin/sh
  args:
    - -c
    - |
      yarn
      yarn test
  env:
    - 'PG_HOST=postgres'
- name: 'docker'
  args: ['build', '-t', 'houstonj1/cloudbuild-compose:latest', '.']
  env:
    - 'DOCKER_BUILDKIT=1'
- name: 'docker'
  entrypoint: /bin/sh
  args:
    - -c
    - |
      docker ps -a
      docker run --network cloudbuild houstonj1/cloudbuild-compose:latest yarn test
  env:
    - 'PG_HOST=postgres'

